name: Build and Publish Docker Image

on:
  workflow_call:
    inputs:
      checkout_main:
        type: boolean
        required: false
    secrets:
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      azure_registry:
        required: true
jobs:
  build:
    name: ${{ github.sha }} # Shows up as Build / <sha> 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.checkout_main && 'main' || null }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: ACR Login
      run: az acr login --name ${{ secrets.AZURE_REGISTRY }}

    - name: Format image tag
      run: echo "IMAGE_TAG=${{ secrets.AZURE_REGISTRY }}/${GITHUB_REPOSITORY#*/}:${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
