name: Build and Publish Docker Image

on:
  workflow_call:
    secrets:
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      azure_registry:
        required: true
jobs:
  build:
    name: Build ${{ github.sha }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: ACR Login
      run: az acr login --name ${{ secrets.AZURE_REGISTRY }}

    - name: Build Image
      run: docker build . --file Dockerfile --tag ${{ secrets.AZURE_REGISTRY }}/${GITHUB_REPOSITORY#*/}:${GITHUB_SHA}

    - name: Publish Image
      run: docker push ${{ secrets.AZURE_REGISTRY }}/${GITHUB_REPOSITORY#*/}:${GITHUB_SHA}
